### ISSUE TITLE
Is possible to change file before upload to server?

### ISSUE THREAD

**Issue by Algorush** [Sopamo/laravel-filepond#69]
Hi, thanks for this plugin.
Can you give me some advice please? The laravel project I'm working with is uploading multiple Obj files to the server via filepond. I haven't quite figured out how filepond works yet. Now there is a task to compress the files on the client side before uploading to the server, or maybe on the server. That is, several files are selected through input, then I need to apply the js transformation function to them, and then new files with a new extension are sent to the server. What filepond method can be used for this?

**Comment by Sopamo** [comment]
Hi, this really is a question about the original [js library](https://github.com/pqina/filepond). But generally, "usage" questions like yours are better asked on https://stackoverflow.com
Most GitHub issue trackers are reserved for bugs/feature requests.
I'm going to close this issue here, but please try posting your question on StackOverflow and feel free to link it here.
